version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops-web
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: devops_db
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: devops_pass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  db:
    image: postgres:15
    container_name: devops-db
    environment:
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: devops_pass
      POSTGRES_DB: devops_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
